import { useMemo, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { BarChart3, Bell, Bot, Check, ChevronRight, CloudSun, FileText, Leaf, LogOut, Menu, Moon, Settings2, Sparkles, Sun, Tractor, UserRound, X, Zap } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { useAuth } from "@/_core/hooks/useAuth";
import { toast } from "sonner";

const BASE = import.meta.env.BASE_URL;
const activity = [
  { day: "Mon", moisture: 42, activity: 58 }, { day: "Tue", moisture: 49, activity: 64 }, { day: "Wed", moisture: 55, activity: 71 },
  { day: "Thu", moisture: 51, activity: 66 }, { day: "Fri", moisture: 62, activity: 78 }, { day: "Sat", moisture: 68, activity: 82 }, { day: "Sun", moisture: 73, activity: 88 },
];
const crops = [
  { name: "Cotton", health: 92, stage: "Flowering", area: "8.5 acres", color: "#71e6b0" },
  { name: "Soybean", health: 84, stage: "Vegetative", area: "6 acres", color: "#79c8ff" },
  { name: "Wheat", health: 76, stage: "Harvest ready", area: "3.5 acres", color: "#f7c768" },
];
const markets = [
  { name: "Cotton", market: "Nagpur APMC", price: "₹7,420/q", delta: "+4.8%" },
  { name: "Soybean", market: "Latur APMC", price: "₹4,815/q", delta: "+2.2%" },
  { name: "Wheat", market: "Pune APMC", price: "₹2,640/q", delta: "-0.6%" },
];

type Tab = "home" | "farm" | "scan" | "market" | "advisor" | "reports" | "profile";

export default function DemoHub() {
  const { logout } = useAuth();
  const [tab, setTab] = useState<Tab>("home");
  const [dark, setDark] = useState(() => localStorage.getItem("krishai-demo-theme") !== "light");
  const [menuOpen, setMenuOpen] = useState(false);
  const [scanRunning, setScanRunning] = useState(false);
  const [scanDone, setScanDone] = useState(false);
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState("Ask me about your crops, weather, irrigation, or markets. This demo advisor answers instantly.");
  const [profileName, setProfileName] = useState("Demo Administrator");
  const [saved, setSaved] = useState(false);
  const bg = dark ? "bg-[#081426] text-white" : "bg-[#edf4f2] text-[#18313b]";
  const card = dark ? "border-white/10 bg-white/[0.055]" : "border-[#18313b]/10 bg-white/80";
  const muted = dark ? "text-slate-400" : "text-slate-600";
  const nav: Array<[Tab, string, LucideIcon]> = [
    ["home", "Overview", Leaf], ["farm", "My crops", Tractor], ["scan", "AI scan", Sparkles], ["market", "Markets", BarChart3],
    ["advisor", "AI advisor", Bot], ["reports", "Reports", FileText], ["profile", "Profile", UserRound],
  ];
  const activeLabel = nav.find(([key]) => key === tab)?.[1] ?? "Overview";
  const setTheme = (next: boolean) => { setDark(next); localStorage.setItem("krishai-demo-theme", next ? "dark" : "light"); };
  const runScan = () => {
    setScanRunning(true); setScanDone(false);
    window.setTimeout(() => { setScanRunning(false); setScanDone(true); toast.success("Demo AI scan complete: crop looks healthy."); }, 1100);
  };
  const askAdvisor = () => {
    const q = question.trim();
    if (!q) { toast.error("Type a question first."); return; }
    setAnswer(`Demo advisor: For “${q}”, keep soil moisture near 65%, inspect the newest leaves tomorrow morning, and compare local mandi prices before selling.`);
    setQuestion("");
  };
  const goAdmin = () => { window.location.href = `${BASE}?admin=1&from=demo`; };
  const title = useMemo(() => ({ home: "Good morning, Demo Administrator", farm: "Your crop command center", scan: "AI crop health scan", market: "Market intelligence", advisor: "Your agriculture advisor", reports: "Reports & field notes", profile: "Your demo profile" }[tab]), [tab]);
  return <div className={`min-h-screen transition-colors duration-500 ${bg}`}>
    <div className="pointer-events-none fixed inset-0 overflow-hidden opacity-60"><div className="absolute -right-32 -top-24 h-96 w-96 rounded-full border border-emerald-300/20 shadow-[0_0_0_32px_rgba(113,230,176,.04),0_0_0_64px_rgba(113,230,176,.03)] animate-pulse" /><div className="absolute -bottom-40 -left-24 h-96 w-[70vw] rotate-[-12deg] rounded-[50%] border border-sky-300/15" /><div className="absolute left-1/2 top-1/3 h-2 w-2 rounded-full bg-emerald-300 shadow-[0_0_24px_8px_rgba(113,230,176,.45)] animate-ping" /></div>
    <header className={`sticky top-0 z-20 border-b backdrop-blur-xl ${dark ? "border-white/10 bg-[#081426]/85" : "border-slate-900/10 bg-[#edf4f2]/85"}`}><div className="mx-auto flex max-w-7xl items-center gap-3 px-4 py-3 sm:px-6"><button onClick={() => setMenuOpen(true)} className="rounded-xl border border-white/10 p-2 lg:hidden"><Menu className="h-5 w-5" /></button><img src={`${BASE}krishai-logo.svg`} className="h-9 w-9 rounded-xl" /><div><div className="font-display text-sm font-bold text-emerald-300">KrishAI Hub</div><div className={`text-[10px] uppercase tracking-[.22em] ${muted}`}>Demo intelligence workspace</div></div><div className="ml-auto flex items-center gap-2"><button onClick={() => toast("Demo notifications: 3 weather and crop updates ready.")} className="rounded-xl border border-white/10 p-2"><Bell className="h-4 w-4" /></button><button onClick={() => setTheme(!dark)} className="rounded-xl border border-white/10 p-2">{dark ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}</button><button onClick={goAdmin} className="hidden rounded-xl bg-emerald-400 px-3 py-2 text-xs font-bold text-[#082019] sm:block">Admin console</button><button onClick={() => void logout()} className="rounded-xl border border-white/10 p-2"><LogOut className="h-4 w-4" /></button></div></div></header>
    <div className="mx-auto flex max-w-7xl"><aside className={`hidden min-h-[calc(100vh-65px)] w-60 shrink-0 border-r px-4 py-6 lg:block ${dark ? "border-white/10" : "border-slate-900/10"}`}><div className={`mb-5 rounded-2xl border p-4 ${card}`}><div className="mb-2 flex items-center gap-2 text-xs font-bold text-emerald-300"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-300" /> DEMO MODE</div><p className={`text-xs leading-relaxed ${muted}`}>All actions on this workspace are fictional and saved in this browser only.</p></div>{nav.map(([key, label, Icon]) => <button key={key} onClick={() => setTab(key)} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm transition ${tab === key ? "bg-emerald-400/15 text-emerald-300" : `${muted} hover:bg-white/5`}`}><Icon className="h-4 w-4" />{label}</button>)}<button onClick={goAdmin} className={`mt-8 flex w-full items-center gap-3 rounded-xl border px-3 py-2.5 text-left text-xs ${card}`}><Settings2 className="h-4 w-4" />Switch to admin</button></aside>
      {menuOpen && <div className="fixed inset-0 z-40 bg-black/50 lg:hidden" onClick={() => setMenuOpen(false)}><div className={`h-full w-72 p-4 ${dark ? "bg-[#0b1b31]" : "bg-white"}`} onClick={e => e.stopPropagation()}><div className="mb-6 flex items-center justify-between"><b>Demo workspace</b><button onClick={() => setMenuOpen(false)}><X className="h-5 w-5" /></button></div>{nav.map(([key, label, Icon]) => <button key={key} onClick={() => { setTab(key); setMenuOpen(false); }} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left ${tab === key ? "bg-emerald-400/15 text-emerald-300" : muted}`}><Icon className="h-4 w-4" />{label}</button>)}</div></div>}
      <main className="min-w-0 flex-1 px-4 py-6 sm:px-8 lg:px-10"><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><div className="mb-2 text-xs font-bold uppercase tracking-[.22em] text-emerald-300">{activeLabel}</div><h1 className="font-display text-2xl font-bold sm:text-4xl">{title}</h1><p className={`mt-2 max-w-2xl text-sm ${muted}`}>A fictional interactive preview of the KrishAI Hub farmer and student experience.</p></div><div className={`rounded-2xl border px-4 py-3 text-xs ${card}`}><div className={muted}>Today in Maharashtra</div><div className="mt-1 flex items-center gap-2 text-lg font-bold"><CloudSun className="h-5 w-5 text-amber-300" /> 28°C <span className="text-xs font-normal text-emerald-300">Good growing window</span></div></div></div>
        {tab === "home" && <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{([ ["Crop health", "86%", "+8.4% this week", Leaf], ["Soil moisture", "68%", "Optimal range", CloudSun], ["Open tasks", "04", "2 due today", Check], ["Market signal", "Strong", "Cotton +4.8%", Zap] ] as Array<[string, string, string, LucideIcon]>).map(([label, value, note, Icon]) => <div key={String(label)} className={`rounded-3xl border p-5 ${card}`}><Icon className="mb-5 h-5 w-5 text-emerald-300" /><div className={`text-xs uppercase tracking-widest ${muted}`}>{label}</div><div className="mt-2 text-3xl font-bold">{value}</div><div className="mt-1 text-xs text-emerald-300">{note}</div></div>)}</div><div className="mt-5 grid gap-5 xl:grid-cols-[1.5fr_1fr]"><div className={`rounded-3xl border p-5 ${card}`}><div className="mb-4 flex items-center justify-between"><div><h2 className="font-display font-bold">Field activity</h2><p className={`text-xs ${muted}`}>Moisture and activity, last 7 days</p></div><span className="rounded-full bg-emerald-400/10 px-3 py-1 text-xs text-emerald-300">Live demo</span></div><div className="h-64"><ResponsiveContainer width="100%" height="100%"><AreaChart data={activity}><defs><linearGradient id="demoGreen" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#71e6b0" stopOpacity={.5}/><stop offset="100%" stopColor="#71e6b0" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke={dark ? "#ffffff12" : "#17313b18"} vertical={false}/><XAxis dataKey="day" stroke={dark ? "#94a3b8" : "#526d75"} fontSize={11}/><YAxis stroke={dark ? "#94a3b8" : "#526d75"} fontSize={11}/><Tooltip contentStyle={{ background: dark ? "#102238" : "#fff", border: "0", borderRadius: 12, color: dark ? "#fff" : "#17313b" }}/><Area type="monotone" dataKey="activity" stroke="#71e6b0" fill="url(#demoGreen)" strokeWidth={3}/><Area type="monotone" dataKey="moisture" stroke="#79c8ff" fill="transparent" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></div><div className={`rounded-3xl border p-5 ${card}`}><h2 className="font-display font-bold">Today’s checklist</h2><div className="mt-4 space-y-3">{["Inspect cotton leaves", "Review irrigation window", "Compare mandi prices", "Upload field note"].map((item, i) => <button key={item} onClick={() => toast.success(`${item} marked complete in demo.`)} className={`flex w-full items-center gap-3 rounded-2xl border p-3 text-left text-sm ${dark ? "border-white/10 hover:bg-white/5" : "border-slate-900/10 hover:bg-slate-50"}`}><span className={`flex h-6 w-6 items-center justify-center rounded-full text-xs ${i < 2 ? "bg-emerald-400 text-[#082019]" : "bg-white/10 text-emerald-300"}`}>{i < 2 ? <Check className="h-3 w-3" /> : i + 1}</span><span className="flex-1">{item}</span><ChevronRight className="h-4 w-4 opacity-50" /></button>)}</div></div></div></>}
        {tab === "farm" && <div className="grid gap-4 md:grid-cols-3">{crops.map(crop => <div key={crop.name} className={`rounded-3xl border p-5 ${card}`}><div className="mb-5 flex items-start justify-between"><div className="rounded-2xl p-3" style={{ background: `${crop.color}22`, color: crop.color }}><Leaf className="h-5 w-5" /></div><span className="text-xs text-emerald-300">Healthy</span></div><h2 className="font-display text-xl font-bold">{crop.name}</h2><p className={`mt-1 text-sm ${muted}`}>{crop.stage} · {crop.area}</p><div className="mt-6 flex items-center justify-between text-xs"><span className={muted}>Health score</span><b>{crop.health}%</b></div><div className="mt-2 h-2 rounded-full bg-white/10"><div className="h-full rounded-full" style={{ width: `${crop.health}%`, background: crop.color }} /></div><button onClick={() => { setTab("scan"); toast(`AI scan ready for ${crop.name}.`); }} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-400/15 py-2.5 text-xs font-bold text-emerald-300">Scan this crop <ChevronRight className="h-4 w-4" /></button></div>)}</div>}
        {tab === "scan" && <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className={`rounded-3xl border p-6 ${card}`}><div className="mb-6 flex items-center gap-3"><div className="rounded-2xl bg-emerald-400/15 p-3 text-emerald-300"><Sparkles className="h-6 w-6" /></div><div><h2 className="font-display text-xl font-bold">Demo crop scanner</h2><p className={`text-sm ${muted}`}>No upload or server needed for this preview.</p></div></div><div className="flex min-h-64 items-center justify-center rounded-3xl border border-dashed border-emerald-300/25 bg-emerald-300/5"><div className="text-center"><Leaf className={`mx-auto h-14 w-14 text-emerald-300 ${scanRunning ? "animate-spin" : ""}`} /><p className="mt-4 font-semibold">{scanRunning ? "Analyzing crop texture…" : scanDone ? "Scan complete" : "Ready for a demo scan"}</p><p className={`mt-1 text-xs ${muted}`}>{scanDone ? "No visible disease pattern detected. Confidence 94%." : "Tap the button to simulate AI vision."}</p></div></div><button onClick={runScan} disabled={scanRunning} className="mt-5 w-full rounded-2xl bg-emerald-400 py-3 font-bold text-[#082019] disabled:opacity-50">{scanRunning ? "Scanning…" : scanDone ? "Run another demo scan" : "Start AI scan"}</button></div><div className={`rounded-3xl border p-6 ${card}`}><h2 className="font-display font-bold">Scan history</h2>{["Cotton · 94% healthy", "Soybean · 88% healthy", "Wheat · 76% healthy"].map((s, i) => <div key={s} className="mt-4 flex items-center gap-3"><span className="h-2 w-2 rounded-full bg-emerald-300" /><span className="flex-1 text-sm">{s}</span><span className={`text-xs ${muted}`}>{i + 1}d ago</span></div>)}</div></div>}
        {tab === "market" && <div className="grid gap-4 md:grid-cols-3">{markets.map(m => <div key={m.name} className={`rounded-3xl border p-5 ${card}`}><div className="flex items-start justify-between"><div><div className={`text-xs ${muted}`}>{m.market}</div><h2 className="mt-1 font-display text-xl font-bold">{m.name}</h2></div><span className={`text-xs ${m.delta.startsWith("+") ? "text-emerald-300" : "text-rose-300"}`}>{m.delta}</span></div><div className="mt-7 text-3xl font-bold">{m.price}</div><button onClick={() => toast.success(`${m.name} alert enabled in demo.`)} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl border border-white/10 py-2.5 text-xs font-bold">Set price alert <Bell className="h-3.5 w-3.5" /></button></div>)}</div>}
        {tab === "advisor" && <div className={`mx-auto max-w-3xl rounded-3xl border p-6 ${card}`}><div className="flex items-center gap-3"><div className="rounded-2xl bg-violet-400/15 p-3 text-violet-300"><Bot className="h-6 w-6" /></div><div><h2 className="font-display text-xl font-bold">KrishAI advisor</h2><p className={`text-sm ${muted}`}>Fictional instant answers for the demo workspace.</p></div></div><div className="mt-7 rounded-2xl bg-violet-400/10 p-4 text-sm leading-relaxed">{answer}</div><div className="mt-4 flex gap-2"><input value={question} onChange={e => setQuestion(e.target.value)} onKeyDown={e => e.key === "Enter" && askAdvisor()} placeholder="e.g. When should I irrigate cotton?" className={`min-w-0 flex-1 rounded-2xl border bg-transparent px-4 py-3 text-sm outline-none ${dark ? "border-white/10" : "border-slate-900/10"}`} /><button onClick={askAdvisor} className="rounded-2xl bg-emerald-400 px-5 py-3 text-sm font-bold text-[#082019]">Ask</button></div></div>}
        {tab === "reports" && <div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className={`rounded-3xl border p-5 ${card}`}><h2 className="font-display font-bold">Weekly field report</h2><p className={`mt-1 text-sm ${muted}`}>Generated from fictional demo signals.</p><div className="mt-5 h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={activity}><CartesianGrid stroke={dark ? "#ffffff12" : "#17313b18"} vertical={false}/><XAxis dataKey="day" stroke={dark ? "#94a3b8" : "#526d75"} fontSize={11}/><YAxis stroke={dark ? "#94a3b8" : "#526d75"} fontSize={11}/><Tooltip contentStyle={{ background: dark ? "#102238" : "#fff", border: 0, borderRadius: 12 }}/><Bar dataKey="activity" fill="#71e6b0" radius={[6,6,0,0]} /></BarChart></ResponsiveContainer></div><button onClick={() => toast.success("Demo report downloaded.")} className="mt-4 rounded-xl bg-emerald-400 px-4 py-2.5 text-xs font-bold text-[#082019]">Download demo report</button></div><div className={`rounded-3xl border p-5 ${card}`}><h2 className="font-display font-bold">Insights</h2><div className="mt-5 space-y-4 text-sm"><div className="rounded-2xl bg-emerald-400/10 p-4"><b className="text-emerald-300">Positive</b><p className={`mt-1 ${muted}`}>Moisture trend is improving across the last 3 days.</p></div><div className="rounded-2xl bg-amber-400/10 p-4"><b className="text-amber-300">Watch</b><p className={`mt-1 ${muted}`}>Wheat harvest window opens in 5 days.</p></div></div></div></div>}
        {tab === "profile" && <div className="mx-auto max-w-2xl"><div className={`rounded-3xl border p-6 ${card}`}><div className="flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-3xl bg-emerald-400 text-xl font-bold text-[#082019]">D</div><div><h2 className="font-display text-xl font-bold">Demo profile</h2><p className={`text-sm ${muted}`}>Administrator · Maharashtra · Fictional workspace</p></div></div><label className={`mt-7 block text-xs font-bold uppercase tracking-widest ${muted}`}>Display name<input value={profileName} onChange={e => setProfileName(e.target.value)} className={`mt-2 w-full rounded-2xl border bg-transparent px-4 py-3 text-sm outline-none ${dark ? "border-white/10" : "border-slate-900/10"}`} /></label><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className={`rounded-2xl p-4 ${dark ? "bg-white/5" : "bg-slate-900/5"}`}><div className={`text-xs ${muted}`}>Role</div><b>Administrator demo</b></div><div className={`rounded-2xl p-4 ${dark ? "bg-white/5" : "bg-slate-900/5"}`}><div className={`text-xs ${muted}`}>Preferred state</div><b>Maharashtra</b></div></div><button onClick={() => { setSaved(true); toast.success("Demo profile saved locally."); window.setTimeout(() => setSaved(false), 2200); }} className="mt-5 rounded-2xl bg-emerald-400 px-5 py-3 text-sm font-bold text-[#082019]">{saved ? "Saved" : "Save demo profile"}</button></div></div>}
      </main></div>
  </div>;
}
